// Every string a person hears or reads lives here (CLAUDE.md). No em dashes:
// toSpeech() strips them from model text, and these are written without them.

// ---------------------------------------------------------------------------
// Spoken
// ---------------------------------------------------------------------------

export const FIRST_MESSAGE = "Hi, this is RelayPay support. I'm an AI assistant. How can I help today?";

/** Spoken at most once per turn while the agent works. It never claims anything. */
export const FILLER_PHRASES = ["One moment while I check that.", "Just a moment while I check that."] as const;

// A fallback may only offer what the system can do at that moment. When the
// agent itself is failing, it cannot take details for a callback, so those
// lines point to the dashboard, which the knowledge base names as the official
// support channel; the call is still recorded and a failed call opens a ticket.
export const SPOKEN = {
  didNotCatch: "Sorry, I didn't catch that. Could you say it again?",
  systemTrouble: "I'm having trouble reaching our systems right now. Please try again in a few minutes, or use the support options in your RelayPay dashboard.",
  databaseDown: "I can't reach our systems right now. Please try again shortly, or use the support options in your RelayPay dashboard.",
  busy: "Our support line is very busy right now. Please try again a little later, or use the support options in your RelayPay dashboard.",
  tooManyTurns: "We've covered a lot on this call. To make sure nothing gets missed, please continue through the support options in your RelayPay dashboard.",
  fallbackDecline: "I can't answer that confidently. I can arrange for a specialist to follow up, or you can use the support options in your RelayPay dashboard.",
  fallbackClarify: "Could you tell me a little more about what you need help with?",
  fallbackLookup: "I couldn't confirm the details of that record just now. Could you read me the reference again?",
  fallbackEscalate: "A specialist needs to help with this. Could I take your name so they can follow up?",
  fallbackCollect: "Sorry, could you say that once more for me?",
  // The sentences code writes from a tool result (DESIGN §6.4).
  staleEta: (arrival: string, statusPhrase: string) => `The record showed an estimated arrival of ${arrival}, which has passed, and it's still ${statusPhrase}.`,
  stalePayout: (scheduled: string, statusPhrase: string) => `The payout was scheduled for ${scheduled}, which has passed, and it's still ${statusPhrase}.`,
  ticketOpened: (reference: string) => `I've opened a ticket for this. Your reference is ${reference}.`,
  callbackBooked: (when: string) => `A specialist will call you on ${when}. You'll get a confirmation email from our booking system.`,
  callbackByEmail: "A specialist will email you to arrange a time.",
  escalatedAlready: "Your case is with a specialist, who will cover this with you.",
  /** Added by code to every inferred answer (DESIGN §8): the agent worked it out, no chunk states it. */
  inferredHedge: "I'm not completely certain about that, so please confirm it in your RelayPay dashboard, or I can arrange for a specialist to check.",
  /** Appended by code to every closing reply; its end, "thanks for calling RelayPay", is the assistant's end-call phrase. */
  goodbye: "Goodbye, and thanks for calling RelayPay.",
  /** Said at once, with the goodbye, when the caller is plainly done (no model). */
  quickGoodbye: "You're welcome.",
  /** Said by Vapi after CALL_SILENCE_TIMEOUT_S of silence, before it ends the call. */
  silenceGoodbye: "I haven't heard anything for a while, so I'll end the call now. You can call back any time.",
} as const;

/**
 * Typed messages on the page (DESIGN §13). Only the lines whose voice wording
 * would be wrong on screen differ; everything else is the same sentence. The
 * turn runner swaps each voice line for its text version.
 */
export const TYPED = {
  greeting: "Hi, I'm RelayPay's AI support assistant. Ask me about payments, payouts, invoices or your account.",
  didNotCatch: "Please type your question and I'll take a look.",
  fallbackCollect: "Sorry, could you type that once more for me?",
  tooManyTurns: "We've covered a lot in this conversation. To make sure nothing gets missed, please continue through the support options in your RelayPay dashboard.",
  goodbye: "Thanks for contacting RelayPay support.",
} as const;

export const VOICE_TO_TYPED: [string, string][] = [
  [SPOKEN.didNotCatch, TYPED.didNotCatch],
  [SPOKEN.fallbackCollect, TYPED.fallbackCollect],
  [SPOKEN.tooManyTurns, TYPED.tooManyTurns],
  [SPOKEN.goodbye, TYPED.goodbye],
];

/** How each unfinished status reads inside the stale-estimate sentence. */
export const STATUS_PHRASES: Record<string, string> = {
  processing: "processing",
  delayed: "marked as delayed",
  scheduled: "scheduled",
  "review required": "under review",
};

// ---------------------------------------------------------------------------
// The web voice page (DESIGN §13)
// ---------------------------------------------------------------------------

export const PAGE = {
  title: "RelayPay Support",
  description: "Talk to RelayPay's AI support assistant, or type your question, about payments, payouts, invoices or your account.",
  logoAlt: "RelayPay",
  headerLabel: "Support",
  available: "Available now",
  heading: "How can we help today?",
  lead: "Ask about payments, payouts, invoices or your account. Type below, or start a voice call.",
  points: [
    { title: "Approved answers", body: "From RelayPay's help content, never a guess." },
    { title: "Payment checks", body: "Share a reference to hear its status." },
    { title: "A specialist when needed", body: "Callbacks for anything a person should handle." },
  ],
  disclosure: "You're talking to an AI assistant. Conversations are logged for quality and follow-up.",
  englishOnly: "English only for now.",
  voice: {
    call: "Call",
    callLabel: "Start a voice call",
    heading: "Voice call with RelayPay support",
    body: "Speak naturally. You can say a reference such as TXN-9001 out loud.",
    endCall: "End call",
    retry: "Try again",
    callAgain: "Call again",
    backToChat: "Back to messages",
    transcriptLabel: "Your call with RelayPay support",
    mute: "Mute",
    unmute: "Unmute",
    mutedStatus: "You're muted",
    status: {
      idle: "Ready when you are.",
      askingMic: "Allow microphone access to start the call.",
      connecting: "Connecting you to RelayPay support",
      listening: "Listening",
      speaking: "The assistant is speaking",
      ending: "Ending the call",
      ended: "The call has ended",
    },
    micBlocked: {
      heading: "Your microphone is blocked",
      body: "To talk to support, allow microphone access for this site in your browser's address bar, then press Try again. You can also type your question instead.",
    },
    connectFailed: {
      heading: "We couldn't connect the call",
      body: "Please check your connection and try again, or type your question instead.",
    },
    dropped: {
      heading: "The call dropped",
      body: "Everything said up to this point was saved.",
    },
    notConfigured: "Voice calls aren't available yet. You can type your question instead, and get the same help.",
  },
  text: {
    logLabel: "Your conversation with RelayPay support",
    you: "You",
    assistant: "RelayPay assistant",
    inputLabel: "Your message",
    placeholder: "Type your question",
    send: "Send message",
    thinking: "Checking",
    hint: "Enter to send, Shift and Enter for a new line",
    suggestionsLabel: "Popular questions",
    suggestions: [
      { kind: "fees", text: "What fees apply to international payments?" },
      { kind: "lookup", text: "Can you check transaction TXN-9001?" },
      { kind: "specialist", text: "My account was restricted and I need help." },
    ],
    counter: (used: number, max: number) => `${used} of ${max} characters`,
    end: "End conversation",
    restart: "Start a new conversation",
    ended: "This conversation has ended.",
    today: "Today",
    endedDivider: "Conversation ended",
    dismiss: "Dismiss",
    errors: {
      rate_limited: "You've sent a lot of messages in a short time. Please wait a few minutes, then try again.",
      busy: "Still working on your last message. Please wait for the reply.",
      too_long: (max: number) => `Please keep your message under ${max.toLocaleString("en-GB")} characters.`,
      ended: "This conversation has ended. Start a new one to continue.",
      not_found: "We couldn't find this conversation. Please start a new one.",
      empty: "Please type your question first.",
      unavailable: "We can't reach our systems right now. Please try again shortly, or use the support options in your RelayPay dashboard.",
      network: "We couldn't send that. Check your connection and try again.",
      bad_request: "Something went wrong sending that. Please try again.",
    },
  },
  summary: {
    heading: "What happens next",
    ticket: (reference: string) => `Your ticket reference is ${reference}.`,
    escalation: (reference: string) => `Your case reference is ${reference}.`,
    booked: (when: string) => `A specialist will call you on ${when}. Look out for the confirmation email from our booking system.`,
    byEmail: "A specialist will email you to arrange a time.",
    nothing: "No ticket or callback was needed. Thanks for contacting RelayPay support.",
    unavailable: "We couldn't load the summary. Anything agreed in the conversation was saved.",
  },
} as const;

// ---------------------------------------------------------------------------
// Emails to the support team (DESIGN §10.3), all in one template
// ---------------------------------------------------------------------------

export const EMAIL = {
  signature: "RelayPay support system",
  manage: "Change what you receive",
  reasons: {
    escalations: "You are receiving this because you are on RelayPay support's list for escalation handoffs.",
    critical: "You are receiving this because you are on RelayPay support's list for critical alerts.",
    warning: "You are receiving this because you are on RelayPay support's list for warnings.",
    test: "You are receiving this because you were added to RelayPay support's notification list.",
    direct: "Our records system could not be reached, so this alert went to the people who were on the list the last time it was checked.",
  },
  handoff: {
    subject: (ref: string, category: string, who: string, when: string | null) => `[Escalation ${ref}] ${category} · ${who} · ${when ? `callback ${when}` : "no callback booked"}`,
    unverified: "unverified caller",
    badge: (ref: string) => `Escalation ${ref}`,
    title: (company: string | null) => (company ? `${company} needs a specialist` : "A customer needs a specialist"),
    introBooked: (when: string) => `A callback is booked for ${when}. Everything the specialist needs is below, so the customer never has to repeat themselves.`,
    introNotBooked: "No callback is booked yet. Please email the customer to arrange a time. Everything you need is below.",
    headings: { caller: "Caller", why: "Why", said: "The customer's last words", told: "What we already told them", lookedUp: "What we looked up", booking: "Booking" },
    labels: { name: "Name", email: "Email", account: "Account", note: "Support note", category: "Category", reason: "Reason", ticket: "Ticket", status: "Status", link: "Calendar booking", asked: "They asked for" },
    notVerified: "Not verified",
    verified: (id: string, company: string, plan: string, status: string, kyc: string) => `Verified as ${id} (${company}), ${plan} plan, account ${status}, identity check ${kyc}`,
    booked: (when: string) => `Booked for ${when}.`,
    notBooked: (why: string) => `Not booked: ${why}.`,
    noTimeChosen: "no time was chosen",
    nothingTold: "Nothing recorded.",
    noLookups: "No lookups.",
    action: "Open the conversation",
  },
  alert: {
    subject: (severity: string, title: string) => `[RelayPay ${severity === "critical" ? "alert" : "warning"}] ${title}`,
    badge: (severity: string) => (severity === "critical" ? "Critical alert" : "Warning"),
    heading: "When it happened",
    intro: (meaning: string, times: string, first: string, minutes: number) => `${meaning} Seen ${times} since ${first}. Repeats are counted, not emailed again, for ${minutes} minutes.`,
    labels: { type: "What happened", severity: "How urgent", seen: "Seen", first: "First seen", last: "Last seen", details: "For your developer" },
    technical: "Technical detail",
    times: (count: number) => `${count} time${count === 1 ? "" : "s"}`,
    action: "Open alerts in the console",
  },
  test: {
    subject: "RelayPay support: test notification",
    badge: "Test",
    title: "Notifications are working",
    intro: (name: string | null) => `${name ? `Hi ${name}, this` : "This"} is a test from the RelayPay support console. Real emails look like this one.`,
    heading: "You will receive",
    none: "Nothing yet: switch on at least one kind of email in the console.",
    kinds: { escalations: "Escalation handoffs, with the customer's details and the booked callback", critical: "Critical alerts, when something needs attention now", warning: "Warnings, when something is worth a look" },
    action: "Open the console",
  },
} as const;

// ---------------------------------------------------------------------------
// The support console (DESIGN §14)
// ---------------------------------------------------------------------------

export const CONSOLE = {
  title: "RelayPay support console",
  product: "Support console",
  team: "Support team",
  nav: {
    groups: { overview: "Overview", work: "Work", improve: "Improve", system: "System" },
    today: "Today",
    escalations: "Escalations",
    conversations: "Conversations",
    knowledge: "Knowledge",
    alerts: "Alerts",
    evals: "Test runs",
    settings: "Settings",
    logout: "Sign out",
    menu: "Menu",
    close: "Close menu",
  },
  health: {
    good: "All systems normal",
    attention: (count: number) => `${count} alert${count === 1 ? "" : "s"} need${count === 1 ? "s" : ""} attention`,
  },
  login: {
    heading: "Welcome back",
    intro: "Sign in to see today's conversations, escalations and alerts.",
    password: "Password",
    submit: "Sign in",
    wrong: "That password is not right.",
    locked: "Too many attempts from this network. Try again in 15 minutes.",
    notConfigured: "Sign-in isn't set up yet. Ask your developer to set a password for the console.",
    footer: "For RelayPay's support team only.",
  },
  undelivered: {
    noRecipients: "Nobody is set to receive alert emails, so alerts are only visible here.",
    failed: (count: number) => `${count} alert${count === 1 ? "" : "s"} could not be emailed. They are all on the Alerts page; if this keeps happening, tell your developer.`,
    action: "Add someone in Settings",
  },
  greeting: (part: "morning" | "afternoon" | "evening") => `Good ${part}`,
  today: {
    heading: "Today",
    intro: "Customer conversations since midnight in Lagos. Test conversations are left out.",
    setup: {
      heading: "Finish setting up",
      progress: (done: number, total: number) => `${done} of ${total} done`,
      intro: "A few things are still needed before this is ready for real customers.",
      recipients: { title: "Choose who gets emails", body: "New cases and alerts are emailed to the people you add in Settings.", action: "Open Settings" },
      voice: { title: "Turn on voice calls", body: "Customers can already type. Voice calls need a one-time setup by your developer." },
      knowledge: { title: "Add RelayPay's help content", body: "The assistant answers product questions from RelayPay's help articles. Your developer loads them once." },
      done: "Done",
    },
    cards: {
      conversations: "Conversations",
      byChannel: (voice: number, typed: number) => `${voice} by voice, ${typed} typed`,
      resolved: "Solved by the assistant",
      ofFinished: (resolved: number, finished: number) => `${resolved} of ${finished} finished conversations`,
      escalations: "Open escalations",
      booked: (count: number) => `${count} callback${count === 1 ? "" : "s"} booked`,
      alerts: "Alerts today",
      critical: (count: number) => (count ? `${count} critical` : "None critical"),
    },
    activity: { heading: "Last 14 days", intro: "Conversations per day, by how they ended.", empty: "No conversations in the last 14 days yet." },
    attention: { heading: "Needs a person", empty: "Nothing is waiting for a person.", viewAll: "All escalations" },
    recent: { heading: "Latest conversations", empty: "No customer conversations yet. Try the support page.", viewAll: "All conversations" },
    speed: {
      heading: "Speed and cost",
      firstText: "First reply on a call",
      vapiTurn: "Voice reply time",
      agentSpend: "AI cost (estimate)",
      vapiCost: "Voice call cost (billed)",
      pair: (p50: string, p95: string) => `${p50} typical, ${p95} slowest 5%`,
      costNote: "The AI cost is an estimate and the voice call cost is the actual bill, so they are shown side by side and never added together.",
    },
    none: "No data yet",
  },
  outcomes: {
    resolved: "Resolved",
    ticket_created: "Ticket",
    escalated: "Escalated",
    abandoned: "Left before booking",
    failed: "Failed",
    open: "In progress",
  } as Record<string, string>,
  channels: { web: "Web call", phone: "Phone", text: "Typed", eval: "Test", mcp_direct: "System check" } as Record<string, string>,
  /** Booking and email states from the records, in words. */
  states: {
    booked: "Booked",
    pending: "Pending",
    failed: "Failed",
    skipped_eval: "Skipped (test)",
    not_requested: "No time chosen",
    sent: "Sent",
    dead: "Gave up",
    done: "Done",
  } as Record<string, string>,
  /** Each kind of alert, for the team: what it is, and what it means for customers. */
  alertTypes: {
    auth_failure: { title: "Blocked an unrecognised request", meaning: "Something tried to use the system without permission and was turned away. Nothing to do unless it keeps happening." },
    bad_vapi_payload: { title: "Voice call data not understood", meaning: "The voice service sent something the system couldn't read, so calls may be affected. Tell your developer." },
    agent_error: { title: "The assistant ran into a problem", meaning: "A customer got a standard reply instead of an answer. If it repeats, tell your developer." },
    agent_timeout: { title: "The assistant took too long", meaning: "A customer got a standard reply because the answer took too long." },
    agent_limit: { title: "The assistant hit a safety limit", meaning: "A reply was stopped by a limit on cost or length, and the customer got a standard reply." },
    mcp_unreachable: { title: "Account checks unavailable", meaning: "The assistant couldn't check records, so customers were offered a specialist instead." },
    tool_error: { title: "A record check failed", meaning: "The assistant couldn't finish checking a record for a customer." },
    retrieval_degraded: { title: "Help search running in a reduced mode", meaning: "Answers may be less complete until it recovers." },
    booking_failed: { title: "A callback couldn't be booked", meaning: "Arrange a time with the customer by email. The case is in Escalations." },
    notification_failed: { title: "An email to the team wasn't sent", meaning: "Make sure someone is set to receive it in Settings." },
    job_dead: { title: "A booking or email gave up", meaning: "It was tried several times and failed. Check the case in Escalations." },
    budget_exceeded: { title: "Daily AI budget reached", meaning: "Customers get a busy message until tomorrow." },
    vapi_hang: { title: "Voice calls are going quiet", meaning: "Several callers recently waited in silence for an answer, so voice replies are slower than they should be." },
    gate_fallback: { title: "A reply was held back", meaning: "A safety check stopped a reply, and the customer got a standard one instead." },
    rate_limited: { title: "Too many messages from one visitor", meaning: "Someone sent a lot of messages quickly and was asked to wait." },
  } as Record<string, { title: string; meaning: string }>,
  escalations: {
    heading: "Escalations",
    intro: "Cases the assistant handed to a person, soonest callback first. Every status change is recorded.",
    showOpen: "Open",
    showAll: "All",
    columns: ["Case", "Customer", "Why", "Callback", "Booking", "Email", "Status"],
    notBooked: "Not booked",
    age: (age: string) => `${age} ago`,
    statuses: { open: "Open", "in progress": "In progress", closed: "Closed" } as Record<string, string>,
    saved: "Saved",
    saveFailed: "Not saved. Try again.",
    empty: "No open escalations. Everything handed to a person has been dealt with.",
    emptyAll: "No escalations yet.",
    count: (count: number) => `${count} ${count === 1 ? "case" : "cases"}`,
    select: "Select a case to see who to call, when, and why.",
    selectTitle: "Nothing selected",
    notFound: "No such escalation.",
    back: "All escalations",
    why: "Why a person is needed",
    callback: "Callback",
    booked: "Booked",
    asked: (text: string) => `Asked for "${text}"`,
    bookingFailed: (reason: string) => `Not booked: ${reason}`,
    handoff: "Email to the team",
    customer: "Customer",
    contact: "Contact",
    verified: (id: string) => `Verified as ${id}`,
    unverified: "Not verified",
    status: "Status",
    history: "Status history",
    historyLine: (from: string, to: string) => `${from} to ${to}`,
    noHistory: "No changes yet.",
    transcript: "The conversation",
    openConversation: "Open the full conversation",
    ticket: "Ticket",
  },
  conversations: {
    heading: "Conversations",
    intro: "The latest 100 conversations. Open one to read it and see what the assistant checked.",
    all: "All customers",
    empty: "No conversations yet.",
    count: (count: number) => `${count} ${count === 1 ? "conversation" : "conversations"}`,
    search: "Search conversations",
    searchPlaceholder: "Search what was said",
    clear: "Clear",
    noMatch: (search: string) => `Nothing matches "${search}".`,
    select: "Select a conversation to read it, and to see what the assistant checked before each reply.",
    selectTitle: "Nothing selected",
    silent: "No words recorded",
    turns: (count: number) => `${count} ${count === 1 ? "reply" : "replies"}`,
  },
  conversation: {
    back: "All conversations",
    whatHappened: "What happened",
    nothingHappened: "Answered without looking anything up.",
    outcome: "Outcome",
    customer: "Customer",
    verifiedAs: (id: string) => `Verified as ${id}`,
    notVerified: "Not verified",
    numbers: "Speed and cost",
    replies: "Replies",
    firstReply: "First reply, typical",
    agentSpend: "AI cost (estimate)",
    vapiCost: "Voice call cost (billed)",
    endedBy: "How it ended",
    endings: {
      "customer-ended-call": "The customer hung up",
      "assistant-ended-call": "The assistant said goodbye",
      "assistant-said-end-call-phrase": "The assistant said goodbye",
      "silence-timed-out": "The line went quiet",
      "exceeded-max-duration": "Reached the time limit",
      "customer-ended": "The customer ended the chat",
      idle: "The customer left the page",
      closed: "Ended on the page",
    } as Record<string, string>,
    started: "Started",
    openEscalation: "Open the escalation",
    actions: {
      search_knowledge_base: "Searched the knowledge base",
      lookup_customer: "Checked who the customer is",
      lookup_transaction: "Looked up a transaction",
      lookup_payout: "Looked up a payout",
      find_callback_slots: "Found callback times",
      create_support_ticket: "Opened a ticket",
      create_escalation: "Handed the case to a specialist",
      log_conversation_event: "Noted an event",
    } as Record<string, string>,
    results: {
      ok: "done",
      found: "found",
      verified: "verified",
      created: "created",
      existing: "already existed",
      not_found: "not found",
      refused: "not their account",
      invalid_input: "not understood",
      error: "failed",
    } as Record<string, string>,
    caller: "Customer",
    agent: "Assistant",
    tools: "Records checked",
    retrieval: "Help articles searched",
    gates: "Safety checks",
    stopped: "Held back by a safety check, never sent",
    behind: "What the assistant checked",
    tickets: "Tickets",
    escalations: "Escalations",
    turns: "Transcript",
    notFound: "No such conversation.",
    meta: { notReported: "Not reported" },
    turnLabel: (index: number) => `Reply ${index}`,
    took: (time: string) => `Took ${time}`,
    cost: (amount: string) => `AI cost ${amount} (estimate)`,
    silence: "(silence)",
    failedReply: "Something went wrong, so the customer got a standard reply.",
    /** What kind of reply each was, in words. */
    replyTypes: {
      answer: "Answered",
      clarify: "Asked a question",
      lookup_result: "Checked records",
      ticket_created: "Opened a ticket",
      escalate: "Handed to a person",
      collect_details: "Taking details",
      decline: "Couldn't answer",
      closing: "Said goodbye",
    } as Record<string, string>,
    sources: { fallback: "Standard reply", cheap_check: "Quick reply" } as Record<string, string>,
    rewritten: "Rewritten",
    inferred: "Not certain",
    inferredHint: "Worked out from the help articles rather than stated in them, so the assistant told the customer it wasn't certain.",
    failedStatus: "Failed",
    interrupted: "Interrupted",
    found: "found an answer",
    related: "found something close",
    notFoundResult: "found nothing",
    used: (titles: string) => `Used: ${titles}`,
    removed: (text: string) => `Removed: ${text}`,
    /** The safety checks each reply goes through (DESIGN §6.3), in words. */
    checks: {
      evidence: "Backed by records",
      question: "Asks a question",
      numbers: "Numbers match the records",
      emails: "No unexpected email addresses",
      references: "Reference numbers match",
      amounts: "No amounts before verification",
      internal_notes: "No internal notes",
      after_escalation: "No account details after handover",
      clarify_streak: "Not too many questions in a row",
      stale_summary: "No out-of-date notes",
      eta_by_code: "Dates worded by the system",
      booking_by_code: "Booking worded by the system",
      ticket_by_code: "Ticket worded by the system",
      own_references: "No made-up references",
      sensitive_terms: "No sensitive words",
      review_claim: "No unsupported review claims",
      goodbye_by_code: "Goodbye worded by the system",
      question_last: "Question moved to the end",
      length: "Shortened",
    } as Record<string, string>,
    escalationLine: (reason: string, booking: string, when: string | null, email: string) => `${reason} Callback: ${booking.toLowerCase()}${when ? ` for ${when}` : ""}. Email to the team: ${email.toLowerCase()}.`,
  },
  knowledge: {
    heading: "Knowledge",
    intro: "Teach the assistant. Answer the questions it could not, and post service notices it will mention to customers.",
    tabs: { gaps: "Questions to answer", answers: "Team answers", notices: "Service notices" },
    gaps: {
      intro: "Questions the assistant declined or could only half answer, grouped by the nearest part of the knowledge base.",
      asked: (count: number) => `Asked ${count} time${count === 1 ? "" : "s"}`,
      nearest: "Nearest section",
      noMatch: "No close section",
      answer: "Answer this",
      empty: "No unanswered questions. When the assistant declines something, it will appear here.",
    },
    answers: {
      intro: "Approved answers the assistant uses like the knowledge base. Switch one off to take it out of use at once.",
      add: "Write an answer",
      empty: "No team answers yet. Answer a question from the first tab, or write one here.",
      used: (count: number) => `Used in ${count} answer${count === 1 ? "" : "s"}`,
      from: "From a customer's question",
    },
    notices: {
      intro: "Short, current news the assistant mentions when it bears on a question: an outage, a delay, a change. Each one expires.",
      add: "Post a notice",
      empty: "No service notices.",
      until: (when: string) => `Shown until ${when}`,
      expired: "Expired",
      noExpiry: "No end date",
    },
    form: {
      question: "Question",
      questionHint: "Write it the way a customer would ask it.",
      headline: "Headline",
      answer: "Answer",
      answerHint: "Plain words, a few sentences. The assistant says only what this says.",
      notice: "What customers should know",
      expires: "Show for",
      expiresOptions: [
        { label: "1 day", hours: 24 },
        { label: "3 days", hours: 72 },
        { label: "1 week", hours: 168 },
        { label: "30 days", hours: 720 },
      ],
      save: "Save",
      saving: "Saving",
      cancel: "Cancel",
      saved: "Saved. The assistant can use it now.",
      failed: "Not saved. Check the fields and try again.",
    },
    active: "In use",
    inactive: "Switched off",
    justNow: "Just now",
    turnOn: "Switch on",
    turnOff: "Switch off",
  },
  alerts: {
    heading: "Alerts",
    intro: "Problems the system noticed, counted rather than repeated. Critical alerts and warnings are emailed to the people in Settings.",
    counts: { critical: "Critical", warning: "Warnings", info: "For information" },
    columns: ["What happened", "How urgent", "Seen", "Last seen", "Emailed"],
    severities: { critical: "Critical", warning: "Warning", info: "For information" } as Record<string, string>,
    times: (count: number) => `${count} ${count === 1 ? "time" : "times"}`,
    notEmailed: "Not emailed",
    technical: "For your developer",
    empty: "No alerts. Everything is running normally.",
  },
  evals: {
    heading: "Test runs",
    intro: "Practice conversations run through the real assistant and checked against the records, before anything changes for customers. No real bookings or emails are made.",
    runs: "Runs",
    runColumns: ["Started", "Name", "AI model", "Passed", "Reply time, typical / slowest", "AI cost (estimate)"],
    matrix: "Pass rate per test, from the latest three full runs of each AI model",
    matrixColumns: ["Test", "AI model", "Passed"],
    running: "Running",
    stopped: "Stopped",
    passedOf: (passed: number, runs: number) => `${passed} of ${runs}`,
    empty: "No test runs yet. Your developer starts them.",
  },
  /** AI models by their product names. */
  models: { "claude-sonnet-5-5": "Claude Sonnet 5.5", "claude-haiku-4-5-20251001": "Claude Haiku 4.5" } as Record<string, string>,
  settings: {
    heading: "Settings",
    intro: "Who hears about what, and how the assistant is set up.",
    notifications: {
      heading: "Email notifications",
      intro: "Choose who gets each kind of email. Changes apply to the next email.",
      kinds: {
        escalations: { label: "Escalation handoffs", hint: "A new case, with the customer's details and callback" },
        critical_alerts: { label: "Critical alerts", hint: "Something needs attention now" },
        warning_alerts: { label: "Warnings", hint: "Worth a look when there is time" },
      },
      add: "Add person",
      email: "Email address",
      emailPlaceholder: "name@company.com",
      name: "Name (optional)",
      adding: "Adding",
      added: "Added.",
      exists: "That address is already on the list.",
      invalid: "Enter a valid email address.",
      remove: "Remove",
      removeConfirm: (email: string) => `Remove ${email} from all emails?`,
      removed: "Removed.",
      paused: "Paused",
      active: "Receiving",
      pause: "Pause",
      resume: "Resume",
      test: "Send test",
      testing: "Sending",
      testSent: (email: string) => `Test email sent to ${email}.`,
      testFailed: "The test email could not be sent. Ask your developer to check the email settings.",
      saved: "Saved.",
      saveFailed: "Not saved. Try again.",
      empty: "Nobody receives emails yet. Add the first person above.",
      missing: (kinds: string) => `Nobody receives ${kinds}.`,
    },
    system: {
      heading: "How this is set up",
      model: "AI model",
      voice: "Voice calls",
      voiceReady: "Switched on",
      voiceMissing: "Not switched on yet",
      knowledge: "Help content",
      knowledgeChunks: (count: number, team: number) => `${count} articles, ${team} written by your team`,
      sender: "Emails sent from",
      notSet: "Not set",
    },
  },
} as const;
