import "dotenv/config";

import { writeFileSync } from "node:fs";

import { DEFAULT_AGENT_MODEL } from "../src/lib/constants";
import { closePool, queryDb } from "../src/lib/db";

// The testing evidence (DESIGN §22), generated from the evaluations table,
// never written by hand. The exact headers the brief asks for, and the nine
// rows in the brief's order. Notes point to FAILURES.md, where every fix is
// recorded as it happened.
// Usage: npm run evidence -- [--model claude-sonnet-5-5]

const ROWS: { key: string; testCase: string; notes: string }[] = [
  {
    key: "knowledge_answer",
    testCase: "Knowledge-Grounded Answer",
    notes:
      "The brief lists five fee factors; the knowledge base names three (transaction type, corridor, payment method), so the agent says only those (DESIGN §18.3). Retrieval threshold measured, not picked (evals/retrieval-calibration.md); ranking fix in FAILURES 15. A benchmark miss here was a Claude Code program that never started within the deadline (FAILURES 36).",
  },
  { key: "clarify", testCase: "Clarifying Question", notes: "Clarify streak capped at two in code (the clarify_cap edge case); a failed clarifying question now falls back to a clarifying question, so the cap holds (FAILURES 23)." },
  { key: "customer_lookup", testCase: "Customer Lookup", notes: "Verification needs two identifiers that agree; contact details are never returned by the tool. One start-up stall hit this scenario once (FAILURES 16). The identity rule was reworded after Haiku asked for a third identifier (FAILURES 24)." },
  { key: "transaction_payout_lookup", testCase: "Transaction or Payout Lookup", notes: "The stale summary and the passed estimate are handled in code (FAILURES 4, 6, 9, 10); thinking turned off for Haiku (FAILURES 5)." },
  { key: "ticket", testCase: "Ticket Creation", notes: "Idempotent on a unique key; the reference is written by code from the tool result. The prompt now opens the ticket without a reference when the caller has none (FAILURES 24)." },
  {
    key: "escalation",
    testCase: "Human Escalation",
    notes:
      "Email read-back was blocked by the email gate until FAILURES 18 was fixed. Real Cal.com booking and handoff email proven on 2026-09-29 by a one-off live check (DESIGN §20), since removed with the other one-off scripts. When a benchmark run missed it, the confirmation turn hit the 14 s deadline after a slow program start and a second slot check (FAILURES 36, 37); the caller heard the fallback, not silence.",
  },
  {
    key: "unsupported",
    testCase: "Unsupported Question",
    notes: "Checks widened to the brief's wording (FAILURES 17), then tightened to one sentence after a false pass elsewhere (FAILURES 21). The prompt now offers to check the caller's own payout after the general answer (FAILURES 24).",
  },
  { key: "voice", testCase: "Voice Flow", notes: "Manual, on the deployed page (DESIGN §18.2); entered as evaluations with channel voice." },
  {
    key: "logging",
    testCase: "Logging",
    notes:
      "Compares, tool by tool, what the SDK saw with what the MCP server logged (FAILURES 20). A run fails this row whenever another scenario's turn failed to create its record, so it follows the misses above rather than adding new ones. Every conversation, eval runs included, now ends with a final status and summary (FAILURES 31).",
  },
];

function cell(text: string | null | undefined): string {
  return (text ?? "").replace(/\|/g, "/").replace(/\s+/g, " ").trim();
}

async function main(): Promise<void> {
  const index = process.argv.indexOf("--model");
  const model = index >= 0 ? process.argv[index + 1]! : (process.env.AGENT_MODEL?.trim() ?? DEFAULT_AGENT_MODEL);

  const latestRun = (
    await queryDb<{ id: string; created_at: string; passed: number; total: number }>(
      `select id, created_at::text, passed, total from support_agent.eval_runs
        where model = $1 and finished_at is not null and total >= 10 order by created_at desc limit 1`,
      [model],
    )
  ).rows[0];
  if (!latestRun) throw new Error(`No finished full eval run for ${model}. Run npm run eval first.`);

  // The latest three: earlier benchmark runs on superseded code stay in the table
  // as history but are not what the submitted code scored (FAILURES 21).
  const benchmark = await queryDb<{ scenario_key: string; runs: number; passes: number }>(
    `with latest as (
       select id from support_agent.eval_runs
        where model = $1 and label = 'benchmark' and finished_at is not null
        order by created_at desc limit 3
     )
     select e.scenario_key, count(*)::int as runs, count(*) filter (where e.passed)::int as passes
       from support_agent.evaluations e join latest on latest.id = e.eval_run_id
      group by e.scenario_key`,
    [model],
  );
  const benchmarkBy = new Map(benchmark.rows.map((row) => [row.scenario_key, row]));

  const lines = [
    "# Testing evidence",
    "",
    `Generated by \`npm run evidence\` on ${new Date().toISOString()} from the \`evaluations\` table: the latest full eval run for ${model} (${latestRun.id}, ${latestRun.passed}/${latestRun.total} passed, ${latestRun.created_at}), in text mode through the same runTurn() the Vapi route calls, with sandboxed side effects. "Benchmark" counts the latest three benchmark runs for the same model.`,
    "",
    "| Test case | Expected result | Actual result | Passed? | Notes or fix made |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const row of ROWS) {
    const evaluation = (
      await queryDb<{ expected_behavior: string; actual_behavior: string; passed: boolean; notes: string | null; channel: string }>(
        row.key === "voice"
          ? `select expected_behavior, actual_behavior, passed, notes, channel from support_agent.evaluations where channel = 'voice' order by created_at desc limit 1`
          : `select expected_behavior, actual_behavior, passed, notes, channel from support_agent.evaluations where eval_run_id = $1 and scenario_key = $2 limit 1`,
        row.key === "voice" ? [] : [latestRun.id, row.key],
      )
    ).rows[0];
    if (!evaluation) {
      lines.push(`| ${row.testCase} | ${row.key === "voice" ? "Speech in, spoken reply out, and the conversation and tool calls are in Supabase." : ""} | Not yet run. | Not yet | ${cell(row.notes)} |`);
      continue;
    }
    const bench = benchmarkBy.get(row.key);
    const passed = `${evaluation.passed ? "Yes" : "No"}${bench ? ` (benchmark ${bench.passes}/${bench.runs})` : ""}`;
    const notes = [row.notes, evaluation.notes && !evaluation.passed ? `This run: ${evaluation.notes}` : null].filter(Boolean).join(" ");
    lines.push(`| ${row.testCase} | ${cell(evaluation.expected_behavior)} | ${cell(evaluation.actual_behavior).slice(0, 900)} | ${passed} | ${cell(notes)} |`);
  }
  lines.push("");
  writeFileSync("docs/testing-evidence.md", `${lines.join("\n")}\n`);
  console.log(lines.join("\n"));
}

main()
  .catch((error: unknown) => {
    console.error("Evidence table failed:", error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  })
  .finally(closePool);
