import "dotenv/config";

import { writeFileSync } from "node:fs";

import { closePool, queryDb } from "../src/lib/db";

// Reads what Phase 0 recorded and prints the numbers its exit check asks for
// (DESIGN §18.1): time to first audio cold and warm, spawn and MCP connect
// time, the negotiated MCP protocol version, and the real Vapi path and
// payload. Only real calls count: simulated and probe conversations are left
// out of the latency figures. Nothing here is estimated; a figure with no data
// says so.
// Usage: npm run phase0:report -- [--since 2026-09-29T00:00:00Z]

type Turn = {
  vapi_call_id: string;
  channel: string;
  turn_index: number;
  status: string;
  reply_source: string | null;
  ttft_ms: number | null;
  total_ms: number | null;
  timings: Record<string, number | string | null>;
  created_at: string;
};

function percentile(values: number[], p: number): number | null {
  if (!values.length) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const rank = Math.ceil((p / 100) * sorted.length) - 1;
  return sorted[Math.min(Math.max(rank, 0), sorted.length - 1)]!;
}

function line(label: string, values: number[]): string {
  if (!values.length) return `| ${label} | no data | | |`;
  return `| ${label} | ${percentile(values, 50)} ms | ${percentile(values, 95)} ms | ${values.length} |`;
}

async function main(): Promise<void> {
  const index = process.argv.indexOf("--since");
  const since = index >= 0 ? process.argv[index + 1]! : "1970-01-01T00:00:00Z";

  const turns = (
    await queryDb<Turn>(
      `select c.vapi_call_id, c.channel, t.turn_index, t.status, t.reply_source, t.ttft_ms, t.total_ms, t.timings, t.created_at::text
         from support_agent.conversation_turns t
         join support_agent.conversations c on c.id = t.conversation_id
        where c.channel in ('web', 'phone') and c.vapi_call_id not like 'simulated-%' and t.created_at >= $1
        order by t.created_at`,
      [since],
    )
  ).rows;

  const reports = (
    await queryDb<{ vapi_call_id: string; report: { artifact?: { performanceMetrics?: { turnLatencies?: Record<string, number>[] } } } }>(
      `select vapi_call_id, raw_end_report as report from support_agent.conversations
        where raw_end_report is not null and channel in ('web', 'phone') and vapi_call_id not like 'simulated-%' and created_at >= $1`,
      [since],
    )
  ).rows;

  const handshakes = (
    await queryDb<{ metadata: Record<string, unknown> }>(
      `select metadata from support_agent.conversation_events where event_type = 'mcp_handshake' and created_at >= $1 order by created_at`,
      [since],
    )
  ).rows.map((row) => row.metadata);

  const sample = (
    await queryDb<{ metadata: unknown }>(
      `select e.metadata from support_agent.conversation_events e join support_agent.conversations c on c.id = e.conversation_id
        where e.event_type = 'vapi_payload_sample' and c.vapi_call_id not like 'simulated-%' and e.created_at >= $1
        order by e.created_at desc limit 1`,
      [since],
    )
  ).rows[0]?.metadata;

  const agentTurns = turns.filter((turn) => turn.reply_source !== "cheap_check");
  const cold = agentTurns.filter((turn) => turn.timings.process_first_turn === 1);
  const warm = agentTurns.filter((turn) => turn.timings.process_first_turn === 0);
  const numbers = (list: Turn[], pick: (turn: Turn) => unknown) => list.map(pick).filter((value): value is number => typeof value === "number");
  const vapiTurns = reports.flatMap((row) => row.report.artifact?.performanceMetrics?.turnLatencies ?? []);
  const vapi = (key: string) => vapiTurns.map((turn) => turn[key]).filter((value): value is number => typeof value === "number");

  const versions = [...new Set(handshakes.map((meta) => `${String(meta.method)}: requested ${String(meta.requested_protocol_version)}, header ${String(meta.protocol_version_header)}`))];
  const clients = [...new Set(handshakes.map((meta) => JSON.stringify(meta.client_info)).filter((value) => value !== "null"))];

  const out = [
    `# Phase 0 measurements`,
    ``,
    `Generated by \`npm run phase0:report\` on ${new Date().toISOString()} from rows since ${since}.`,
    `Real calls only: ${new Set(turns.map((turn) => turn.vapi_call_id)).size} calls, ${turns.length} turns (${agentTurns.length} reached the agent), ${reports.length} end-of-call reports.`,
    ``,
    `## Server side, per turn (our timings)`,
    ``,
    `| Measure | p50 | p95 | n |`,
    `| --- | --- | --- | --- |`,
    line("First streamed text, cold (first turn in the process)", numbers(cold, (turn) => turn.ttft_ms)),
    line("First streamed text, warm", numbers(warm, (turn) => turn.ttft_ms)),
    line("Final text, cold", numbers(cold, (turn) => turn.total_ms)),
    line("Final text, warm", numbers(warm, (turn) => turn.total_ms)),
    line("SDK spawn and MCP connect (query() to init), cold", numbers(cold, (turn) => turn.timings.init_ms)),
    line("SDK spawn and MCP connect (query() to init), warm", numbers(warm, (turn) => turn.timings.init_ms)),
    line("First tool call started, warm", numbers(warm, (turn) => turn.timings.first_tool_use_ms)),
    line("Agent result, warm", numbers(warm, (turn) => turn.timings.result_ms)),
    ``,
    `## Vapi's own latency, per turn (end-of-call reports)`,
    ``,
    `| Measure | p50 | p95 | n |`,
    `| --- | --- | --- | --- |`,
    line("Turn latency (Vapi's time to first audio)", vapi("turnLatency")),
    line("Model latency (our endpoint, as Vapi saw it)", vapi("modelLatency")),
    line("Voice latency", vapi("voiceLatency")),
    line("Transcriber latency", vapi("transcriberLatency")),
    line("Endpointing latency", vapi("endpointingLatency")),
    ``,
    `## MCP`,
    ``,
    versions.length ? versions.map((version) => `- ${version}`).join("\n") : "- no handshake recorded",
    clients.length ? `- clients: ${clients.join(", ")}` : "",
    ``,
    `## Vapi request`,
    ``,
    sample ? `- path: \`${String((sample as { path?: unknown }).path)}\`\n- sample written to \`docs/vapi-payload-sample.json\` (values redacted)` : "- no real call has reached the custom-LLM route yet",
    ``,
    `## Decision gate (DESIGN §4)`,
    ``,
    `Move the turn runner to an always-on host if warm p50 time to first audio is over 3 s, or cold starts are over 8 s.`,
    `Vapi's turn latency is the time-to-first-audio figure; apply the gate to it once there are at least ten real calls.`,
  ].join("\n");

  console.log(out);
  writeFileSync("docs/phase0-measurements.md", `${out}\n`);
  if (sample) writeFileSync("docs/vapi-payload-sample.json", `${JSON.stringify(sample, null, 2)}\n`);
}

main()
  .catch((error: unknown) => {
    console.error("Report failed:", error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  })
  .finally(closePool);
